# Generated by Django 2.0.9 on 2019-01-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
